# Generated by Django 4.2.1 on 2023-11-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
